# Generated by Django 5.0.4 on 2024-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('image', models.ImageField(default='student_images/default.png', upload_to='student_images/')),
                ('location', models.CharField(max_length=250)),
                ('hobby', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
